#!/bin/bash
#
# sd-autocopy - Copies/Moves images automatically from inserted media
#
# Copyright (c) 2011 Lars Michelsen <lm@larsmichelsen.com>
# Copyright (c) 2018 Christian Strassburg <c.strassburg@gmx.de>
#
# License:
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

LOGFILE=/var/log/sd-autocopy
touch $LOGFILE
echo ======================== >> $LOGFILE

# For testing, change it to: [ 1 == 1 ]
if [ 0 == 1 ]; then
   env >> $LOGFILE
   exit 0
fi

# Put this in curly braces and detach the whole block to background
# for not blocking udev during copying.
{
    USER=amcolash
    TARGET=/volume1/homes/amcolash/data/Photos/TODO
    MOUNT=/mnt/sd-autocopy
    FILE_MATCH=".*\.(jpg|cr2|dng|tiff|jpeg|pdf|mkv|avi|mp4|3gp|mpg|mov|mpeg|wma|wmv|vob|mts)$"

    # Catch unset but needed vars - terminate script
    #if [ -z "$ID_SERIAL" ] || [ -z "$DEVNAME" ]; then
    if [ -z "$DEVNAME" ]; then
        echo "Missing env var DEVNAME" >> $LOGFILE
        exit 1
    fi

    echo "Got new device ($DEVNAME), moving images..." >> $LOGFILE

    if [ ! -d "$MOUNT" ]; then
        mkdir -p "$MOUNT"
    fi

    mount $DEVNAME "$MOUNT"

    LINES=$(find "$MOUNT" -regextype posix-egrep -iregex "$FILE_MATCH" -printf "%TY.%Tm.%Td_%p\n")
    DATES=$(echo "$LINES" | cut -d_ -f1 | uniq)

    # First create the directories when missing
    for DATE in $DATES; do
        echo $DATE
        mkdir -p "$TARGET/$DATE"
    done

    # Move the images
    NUM=0
    for LINE in $LINES; do
        DATE=${LINE%%_*}
        FILE=${LINE#*_}
        echo "Moving $FILE to $TARGET/$DATE" >> $LOGFILE
        rsync -avh --remove-source-files "$FILE" "$TARGET/$DATE"
        NUM=$(($NUM+1))
    done

    umount $DEVNAME

    # Fix the permissions for all directories recursive where
    # files have been copied/moved to
    for DATE in $DATES; do
        chown -R $USER.$USER "$TARGET/$DATE"
    done

    # delete all empty directories on SD card
    # find "$MOUNT" -type d -empty -delete

    echo "Finished job. Moved $NUM files." >> $LOGFILE

    # Beep so we know we are all set
    echo 2 >/dev/ttyS1
} &

exit 0
